# Render.yaml configuration for CodeRank application
services:
  # Service Registry (Eureka)
  - type: web
    name: service-registry
    runtime: docker
    dockerfilePath: ./ServiceRegistry/Dockerfile
    port: 8761
    autoDeploy: false
    healthCheckPath: /eureka/apps
    envVars: []

  # API Gateway
  - type: web
    name: api-gateway
    runtime: docker
    dockerfilePath: ./ApiGateway/Dockerfile
    port: 8081
    autoDeploy: false
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  # Auth Service
  - type: web
    name: auth-service
    runtime: docker
    dockerfilePath: ./AuthService/Dockerfile
    port: 8082
    autoDeploy: false
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  # Task Queue Service
  - type: web
    name: task-queue-service
    runtime: docker
    dockerfilePath: ./TaskQueueService/Dockerfile
    port: 8083
    autoDeploy: false
    healthCheckPath: /actuator/health
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka
      - key: SPRING_RABBITMQ_HOST
        fromService:
          type: pserv
          name: rabbitmq
          property: host
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        value: guest
      - key: SPRING_RABBITMQ_PASSWORD
        value: guest

  # Execution Service
  - type: web
    name: execution-service
    runtime: docker
    dockerfilePath: ./ExecutionService/Dockerfile
    port: 8084
    autoDeploy: false
    healthCheckPath: /actuator/health
    disk:
      name: docker-socket
      mountPath: /var/run/docker.sock
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka
      - key: SPRING_RABBITMQ_HOST
        fromService:
          type: pserv
          name: rabbitmq
          property: host
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        value: guest
      - key: SPRING_RABBITMQ_PASSWORD
        value: guest
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  # Message Queue
  - type: pserv
    name: rabbitmq
    runtime: docker
    image: rabbitmq:management
    port: 5672
    autoDeploy: false
    disk:
      name: rabbitmq-data
      mountPath: /var/lib/rabbitmq
    envVars: []

# Database Services
databases:
  - name: postgres
    databaseName: coderank
    user: root
    ipAllowList: []  # All IPs allowed