services:
  # Service Registry (Eureka)
  - type: web
    name: service-registry
    runtime: docker
    dockerfilePath: ./ServiceRegistry/Dockerfile
    plan: starter
    numInstances: 1
    envVars: []

  # API Gateway
  - type: web
    name: api-gateway
    runtime: docker
    dockerfilePath: ./ApiGateway/Dockerfile
    plan: starter
    numInstances: 1
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  # Auth Service
  - type: web
    name: auth-service
    runtime: docker
    dockerfilePath: ./AuthService/Dockerfile
    plan: starter
    numInstances: 1
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  # Task Queue Service
  - type: web
    name: task-queue-service
    runtime: docker
    dockerfilePath: ./TaskQueueService/Dockerfile
    plan: starter
    numInstances: 1
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka
      - key: SPRING_RABBITMQ_HOST
        fromService:
          name: rabbitmq-service
          type: pserv
          property: host
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        value: guest
      - key: SPRING_RABBITMQ_PASSWORD
        value: guest

  # Execution Service
  - type: web
    name: execution-service
    runtime: docker
    dockerfilePath: ./ExecutionService/Dockerfile
    plan: starter
    numInstances: 1
    disk:
      name: docker-socket
      mountPath: /var/run/docker.sock
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka
      - key: SPRING_RABBITMQ_HOST
        fromService:
          name: rabbitmq-service
          type: pserv
          property: host
      - key: SPRING_RABBITMQ_PORT
        value: "5672"
      - key: SPRING_RABBITMQ_USERNAME
        value: guest
      - key: SPRING_RABBITMQ_PASSWORD
        value: guest
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres
          property: password

  # RabbitMQ Service
  - type: pserv
    name: rabbitmq-service
    runtime: docker
    image: rabbitmq
    plan: starter
    disk:
      name: rabbitmq-data
      mountPath: /var/lib/rabbitmq
    envVars: []

databases:
  - name: postgres
    databaseName: coderank
    user: root
    ipAllowList: []