#spring.application.name=ExecutionService
server:
  port: 8084

spring:
  application:
    name: EXECUTION-SERVICE
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/coderank
    #url: jdbc:postgresql://postgres:5432/coderank
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update # Automatically updates schema; use 'validate' or 'none' in production
    show-sql: true

rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}

aws:
  s3:
    bucket: coderank-bucket

code:
  execution:
    memory:
      limit: 512m
    cpu:
      limit: 1.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
      #defaultZone: http://localhost:8761/eureka

