#spring.application.name=ExecutionService
server:
  port: 8084

spring:
  application:
    name: EXECUTION-SERVICE
  cloud:
    discovery:
      enabled: true

rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
#      defaultZone: http://localhost:8761/eureka

