server:
  port: 8082

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/coderank  # Use 'db' as the host for the Docker network
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root} # Username from docker-compose environment
    password: ${SPRING_DATASOURCE_PASSWORD:root} # Password from docker-compose environment
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
      #defaultZone: http://localhost:8761/eureka

jwt:
  secret: "0E654ACB6F4BB78AE105A53BDE251383B7D614C0CD324F83AA8BAD0DF73FD0A4"